blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: ğŸ“ New Article
    description: Submit a new article to be published on the site.
    labels: ["article"]
    file: article.yml
